# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdrza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='radler',
        ),
    ]
