# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrza', '0005_auto_20160318_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woche',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='mdrza.radler'),
        ),
    ]
