# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrza', '0007_auto_20160318_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woche',
            name='di',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='woche',
            name='di_extra',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='woche',
            name='do',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='woche',
            name='do_extra',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='woche',
            name='fr',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='woche',
            name='fr_extra',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='woche',
            name='km',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='woche',
            name='mi',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='woche',
            name='mi_extra',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='woche',
            name='mo',
            field=models.NullBooleanField(default=False),
        ),
    ]
