# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrza', '0009_radler_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='radler',
            name='gesamttage',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
